// source: proto/moonshot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.divvy.moonshot_common.v1.Wallet');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.protobuf.Timestamp');

goog.forwardDeclare('proto.divvy.moonshot_common.v1.WalletStatus');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.divvy.moonshot_common.v1.Wallet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.divvy.moonshot_common.v1.Wallet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.divvy.moonshot_common.v1.Wallet.displayName = 'proto.divvy.moonshot_common.v1.Wallet';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.toObject = function(opt_includeInstance) {
  return proto.divvy.moonshot_common.v1.Wallet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.divvy.moonshot_common.v1.Wallet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.divvy.moonshot_common.v1.Wallet.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createdAt: (f = msg.getCreatedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    modifiedAt: (f = msg.getModifiedAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    trash: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    walletaddress: jspb.Message.getFieldWithDefault(msg, 5, ""),
    walletstatus: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.divvy.moonshot_common.v1.Wallet}
 */
proto.divvy.moonshot_common.v1.Wallet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.divvy.moonshot_common.v1.Wallet;
  return proto.divvy.moonshot_common.v1.Wallet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.divvy.moonshot_common.v1.Wallet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.divvy.moonshot_common.v1.Wallet}
 */
proto.divvy.moonshot_common.v1.Wallet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setModifiedAt(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTrash(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletaddress(value);
      break;
    case 6:
      var value = /** @type {!proto.divvy.moonshot_common.v1.WalletStatus} */ (reader.readEnum());
      msg.setWalletstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.divvy.moonshot_common.v1.Wallet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.divvy.moonshot_common.v1.Wallet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.divvy.moonshot_common.v1.Wallet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getModifiedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTrash();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getWalletaddress();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getWalletstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
*/
proto.divvy.moonshot_common.v1.Wallet.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp modified_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.getModifiedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
*/
proto.divvy.moonshot_common.v1.Wallet.prototype.setModifiedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.clearModifiedAt = function() {
  return this.setModifiedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.hasModifiedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bool trash = 4;
 * @return {boolean}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.getTrash = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.setTrash = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string walletAddress = 5;
 * @return {string}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.getWalletaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.setWalletaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional WalletStatus walletStatus = 6;
 * @return {!proto.divvy.moonshot_common.v1.WalletStatus}
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.getWalletstatus = function() {
  return /** @type {!proto.divvy.moonshot_common.v1.WalletStatus} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.divvy.moonshot_common.v1.WalletStatus} value
 * @return {!proto.divvy.moonshot_common.v1.Wallet} returns this
 */
proto.divvy.moonshot_common.v1.Wallet.prototype.setWalletstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


